<application>
  <component name="ActionsCollector">
    <counts>
      <entry action="$Copy" count="46" />
      <entry action="$Cut" count="7" />
      <entry action="$Delete" count="30" />
      <entry action="$Paste" count="55" />
      <entry action="$SelectAll" count="47" />
      <entry action="$Undo" count="1117" />
      <entry action="ActivateCapturesToolWindow" count="1" />
      <entry action="ActivateStructureToolWindow" count="2" />
      <entry action="Android.BuildApk" count="6" />
      <entry action="Android.CreateResourceDirectory" count="9" />
      <entry action="Android.CreateSampleDataDirectory" count="2" />
      <entry action="Android.GenerateSignedApk" count="2" />
      <entry action="Android.RunAndroidAvdManager" count="6" />
      <entry action="Android.SyncProject" count="13" />
      <entry action="AndroidConnectDebuggerAction" count="4" />
      <entry action="AndroidExtractStyleAction" count="4" />
      <entry action="ChooseRunConfiguration" count="3" />
      <entry action="ClassNameCompletion" count="21" />
      <entry action="CleanGradleProject" count="5" />
      <entry action="CloseAllEditors" count="13" />
      <entry action="CloseAllEditorsButActive" count="1" />
      <entry action="CloseProject" count="19" />
      <entry action="CommentByLineComment" count="87" />
      <entry action="ConsoleView.ClearAll" count="9" />
      <entry action="CopyPaths" count="7" />
      <entry action="CopyReference" count="1" />
      <entry action="CopyUrl" count="1" />
      <entry action="Debug" count="19" />
      <entry action="DelegateMethods" count="1" />
      <entry action="DialogOkAction Enter" count="82" />
      <entry action="DialogOkAction 空格" count="1" />
      <entry action="EditorBackSpace" count="7467" />
      <entry action="EditorChooseLookupItem" count="3096" />
      <entry action="EditorCopy" count="1206" />
      <entry action="EditorCut" count="256" />
      <entry action="EditorDelete" count="48" />
      <entry action="EditorDeleteLine" count="49" />
      <entry action="EditorDown" count="4173" />
      <entry action="EditorDuplicate" count="9" />
      <entry action="EditorEnter" count="2624" />
      <entry action="EditorEscape" count="5" />
      <entry action="EditorIndentSelection" count="17" />
      <entry action="EditorLeft" count="4422" />
      <entry action="EditorLeftWithSelection" count="12" />
      <entry action="EditorPaste" count="1984" />
      <entry action="EditorRight" count="6016" />
      <entry action="EditorRightWithSelection" count="1" />
      <entry action="EditorSelectWord" count="2" />
      <entry action="EditorSplitLine" count="20" />
      <entry action="EditorStartNewLine" count="8" />
      <entry action="EditorTab" count="1000" />
      <entry action="EditorToggleInsertState" count="2" />
      <entry action="EditorUnindentSelection" count="8" />
      <entry action="EditorUp" count="1369" />
      <entry action="EditorUpWithSelection" count="3" />
      <entry action="Exit" count="17" />
      <entry action="FileChooser.NewFolder" count="1" />
      <entry action="Find" count="25" />
      <entry action="FindUsages" count="1" />
      <entry action="Generate" count="13" />
      <entry action="GotoClass" count="2" />
      <entry action="GotoDeclaration" count="10" />
      <entry action="GotoTypeDeclaration" count="1" />
      <entry action="Groovy.Console" count="1" />
      <entry action="HideAllWindows" count="5" />
      <entry action="HippieCompletion" count="12" />
      <entry action="JumpToLastWindow" count="1" />
      <entry action="MakeGradleModule" count="1" />
      <entry action="MakeGradleProject" count="39" />
      <entry action="MaximizeToolWindow" count="2" />
      <entry action="MethodDuplicates" count="1" />
      <entry action="NewAndroidImageAsset" count="18" />
      <entry action="NewAndroidVectorAsset" count="4" />
      <entry action="NewClass" count="37" />
      <entry action="NewDir" count="20" />
      <entry action="NewFile" count="4" />
      <entry action="NewModule" count="2" />
      <entry action="NewModuleInGroup" count="32" />
      <entry action="NewProject" count="6" />
      <entry action="NewScratchFile" count="1" />
      <entry action="NextTemplateVariable" count="10" />
      <entry action="OpenFile" count="33" />
      <entry action="OpenModuleSettings" count="1" />
      <entry action="ReformatCode" count="5" />
      <entry action="RenameElement" count="31" />
      <entry action="RenameFile" count="1" />
      <entry action="ReplaceInPath" count="1" />
      <entry action="Run" count="476" />
      <entry action="SaveAll" count="1959" />
      <entry action="SearchEverywhere" count="12" />
      <entry action="ShowErrorDescription" count="2" />
      <entry action="ShowFilePath" count="4" />
      <entry action="ShowIntentionActions" count="507" />
      <entry action="ShowSettings" count="5" />
      <entry action="SmartTypeCompletion" count="2" />
      <entry action="Stop" count="90" />
      <entry action="SynchronizeCurrentFile" count="1" />
      <entry action="ToggleBookmark" count="2" />
      <entry action="ToggleLineBreakpoint" count="18" />
      <entry action="Vcs.UpdateProject" count="1" />
      <entry action="context.save" count="1" />
 